### PR TITLE
Responsive web

### PR DESCRIPTION
**Pull request by louissmit**
I tweaked the bootstrap responsive stuff a little bit because the image was clipping. And also made it so that its not all stretched out in desktop browser.

But I don't know what you like best so take a look at http://www.karenullrich.info/rnnpoetry/ thats running this branch right now with an untrained model of 500k params.

### CODE REVIEW

**Comment by max-ilse** [comment]
Hey Louis,

I tweaked the layout a bit too. It seems ok now on a variety of scrren sizes. I update the text for twitter with the sucess callback, it is kinda hacky.

**Comment by louissmit** [comment]
Hey, I just pushed this to the server, but I think the twitter button doesnt always show up right now.
I think you need to force a redraw after you get the script.

Also, I think the text needs a little bit more breathing room. Its quite close on the image and needs some vertical spacing between the headline, text and text box.

Also, when things go wrong and you get an alert it doesnt remove the overlay so you can't try again.

How did the interview go and when can I listen to it?

**Comment by louissmit** [comment]
Also, maybe a bigger "Los!" button?

**Comment by max-ilse** [comment]
Tried too improve everything according to your mail. The twitter button is
reintialized with every click on the submit button. Is not pretty but works.

2015-08-13 17:56 GMT+02:00 louissmit notifications@github.com:

**Comment by louissmit** [comment]
Script doesn't work :( Check www.karenullrich.info/rnnpoetry

It doesn't insert the poem into the tweet. I think you should just load the tweetbutton on pageload, but hide it in css.
Then in the success function, alter data-text and reveal it again.

**Pull request merged**
